Replace slashes with dashes in ARCHIVE_TAG, initramfs init update
Slash problem caused by pull requests:

ln: failed to create hard link 'vmlinuz-ntsc-88/merge-a6ec171c.elf'
	=> 'vmlinuz': No such file or directory
Error: Process completed with exit code 1.

Update mode_option reconfig for new initramfs/etc/init.d/rcS.